language: node_js
node_js:
  - "0.10"
rvm:
  - 1.9.3
before_install:
  - npm install -g grunt-cli
  - openssl aes-256-cbc -K $encrypted_8ebea8de894c_key -iv $encrypted_8ebea8de894c_iv -in id_deploy.enc -out id_deploy -d
  - chmod 600 id_deploy
install:
  - npm install
  - gem install bundler
  - bundle install
script:
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "wip/comment-test" ]]; then
      grunt deploy ;
    else
      grunt build ;
    fi
sudo: false
cache:
  directories:
    - node_modules
env:
  global:
  - secure: HZLA3vVnzfADdgh/K0JuSWDLmLvqXSoj5Yvuys4zVGsa//5dQ0URlnzTEBg6hGREbo3YBHuuYslp1/hLBaGwn5ahrlJlCrHiJMOJu4UqGgBJP/aZDZy5x9gcAO8vc8LF/yYx2DEvH3XsWxoSKqynwACtKHhwvJ3TvSH2HKMNI2I=
  - secure: RdHepHHrXs7h9kryyLhak/VMJQfFpjw9/iacEps3ki38qgjQ/FqqNDRvTCqfyoaFxDExIGuS9UC/K4aePCV8jV3L2rw9dkjzlnCJvAGvmnH8heu6dsvgpxFfBC23dwFD6RfGGmKA4LI/Lu3yg270FbC7bk0jh15jbHdUcuW+Jfc=
