# Jekyll Configuration
# --------------------

name                  : milessabin.com
description           : "Miles Sabin"
url                   : "http://milessabin.com"

source                : src/html
posts                 : _posts
layouts               : _layouts
includes              : _includes

destination           : target
plugins               : jekyll_plugins

keep_files            : [ 'css', 'js', 'images', 'fonts' ]

permalink             : /blog/:year/:month/:day/:title/
paginate              : 5
paginate_path         : "blog/page:num/"
excerpt_separator     : '<span class="break"></span>'

safe                  : false
highlighter           : pygments

markdown: redcarpet
redcarpet:
  extensions: [
    "no_intra_emphasis",
    "tables",
    "fenced_code_blocks",
    "autolink",
    "strikethrough",
    "lax_spacing",
    "space_after_headers",
    "superscript",
    "smart"
  ]
